name: Build OpenCL Executable JAR

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      # 第 1 步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第 2 步：设置 Java 环境 (Java 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "gradle"

      # 第 3 步：为 Gradle Wrapper 添加可执行权限
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 第 4 步：使用 Gradle 构建可执行的胖 JAR
      # shadowJar 任务会编译所有 Java 代码并打包所有依赖
      - name: Build with Gradle
        run: ./gradlew shadowJar

      # 第 5 步：上传构件
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TreeCracker-OpenCL-Runner
          # shadowJar 默认将文件输出到 build/libs/ 目录下
          path: build/libs/TreeCracker-OpenCL-1.0.jar
